# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: algoliasearch-jekyll 0.2.3 ruby lib

Gem::Specification.new do |s|
  s.name = "algoliasearch-jekyll"
  s.version = "0.2.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Tim Carry"]
  s.date = "2015-07-16"
  s.description = "Index all your pages and posts to an Algolia index with `jekyll algolia push`"
  s.email = "tim@pixelastic.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".rubocop.yml",
    "Gemfile",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/algoliasearch-jekyll.rb",
    "lib/push.rb",
    "lib/record_extractor.rb",
    "scripts/git_hooks/pre-commit",
    "scripts/git_hooks/pre-push",
    "scripts/run_tests",
    "scripts/update_gem",
    "spec/fixtures/_config.yml",
    "spec/fixtures/_my-collection/collection-item.html",
    "spec/fixtures/_my-collection/collection-item.md",
    "spec/fixtures/_posts/2015-07-02-test-post.md",
    "spec/fixtures/about.md",
    "spec/fixtures/api_key_dir/_algolia_api_key",
    "spec/fixtures/assets/ring.png",
    "spec/fixtures/authors.html",
    "spec/fixtures/excluded.html",
    "spec/fixtures/hierarchy.md",
    "spec/fixtures/weight.md",
    "spec/push_spec.rb",
    "spec/record_extractor_spec.rb",
    "spec/spec_helper.rb",
    "spec/spec_helper_jekyll.rb",
    "spec/spec_helper_simplecov.rb"
  ]
  s.homepage = "https://github.com/algolia/algoliasearch-jekyll"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.6"
  s.summary = "AlgoliaSearch for Jekyll"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<algoliasearch>, ["~> 1.4"])
      s.add_runtime_dependency(%q<awesome_print>, ["~> 1.6"])
      s.add_runtime_dependency(%q<json>, ["~> 1.8"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.6"])
      s.add_development_dependency(%q<guard-rspec>, ["~> 4.6"])
      s.add_development_dependency(%q<jekyll>, ["~> 2.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<rspec>, ["~> 3.0"])
      s.add_development_dependency(%q<rubocop>, ["~> 0.31"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.10"])
    else
      s.add_dependency(%q<algoliasearch>, ["~> 1.4"])
      s.add_dependency(%q<awesome_print>, ["~> 1.6"])
      s.add_dependency(%q<json>, ["~> 1.8"])
      s.add_dependency(%q<nokogiri>, ["~> 1.6"])
      s.add_dependency(%q<guard-rspec>, ["~> 4.6"])
      s.add_dependency(%q<jekyll>, ["~> 2.5"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<rspec>, ["~> 3.0"])
      s.add_dependency(%q<rubocop>, ["~> 0.31"])
      s.add_dependency(%q<simplecov>, ["~> 0.10"])
    end
  else
    s.add_dependency(%q<algoliasearch>, ["~> 1.4"])
    s.add_dependency(%q<awesome_print>, ["~> 1.6"])
    s.add_dependency(%q<json>, ["~> 1.8"])
    s.add_dependency(%q<nokogiri>, ["~> 1.6"])
    s.add_dependency(%q<guard-rspec>, ["~> 4.6"])
    s.add_dependency(%q<jekyll>, ["~> 2.5"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<rspec>, ["~> 3.0"])
    s.add_dependency(%q<rubocop>, ["~> 0.31"])
    s.add_dependency(%q<simplecov>, ["~> 0.10"])
  end
end

