#!/usr/bin/env bash

# Do not commit any focused or excluded tests
if grep --color -r 'spec' -E -e '^( |\t)*(fit|fdescribe|xit|xdescribe)'; then
  echo '✘ You have focused and/or skipped tests'
  exit 1
fi

# Match style guide
rubocop -F './lib/' './spec' || exit 1

# No over-complex methods
./scripts/check_flog
