# frozen_string_literal: true

source 'https://rubygems.org'

gem 'jekyll', '~> 3.7.3'

# Note: jekyll-remote-theme download themes on each run, which makes tests
# really slow. To workaround the issue, I submitted a PR to add a cache duration
# to the download. It hasn't been merged yet, so we're using the PR fork for now
# Once https://github.com/benbalter/jekyll-remote-theme/pull/36 is merged, we'll
# be able to use the official gem
gem 'jekyll-remote-theme',
    git: 'https://github.com/pixelastic/jekyll-remote-theme',
    branch: 'cache'

group :jekyll_plugins do
  gem 'github-pages', '~> 183'
  gem 'jekyll-algolia', path: '../../../'
  gem 'jekyll-feed', '~> 0.6'
  gem 'jekyll-paginate', '~> 1.1'
  gem 'jekyll-tagging', '~> 1.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
