#!/usr/bin/env ruby

build_output = `gem build algoliasearch-jekyll.gemspec`.split("\n")
puts build_output
build_output.select! { |line| line.match(/^  File:/) }

gem_file = build_output[0].gsub('  File: ', '')
puts 'Pushing to rubygems'
push_output = `gem push #{gem_file}`
puts push_output
